import pool from './connection.js';

const sampleCompanies = [
  {
    name: "FrontLinesMedia (FLM)",
    industry: "E-Learning",
    location: "Somajiguda, Hyderabad",
    size: "51-200",
    founded_year: 2021,
    website: "https://www.frontlinesedutech.com",
    description:
      "Largest Telugu ed-tech, job-oriented training, placement support",
  },
  {
    name: "Deloitte India",
    industry: "Consulting",
    location: "Mumbai",
    size: "15,000+",
    founded_year: 1992,
    website: "https://www2.deloitte.com/in/en.html",
    description: "Professional services, audit, tax, consulting",
  },
  {
    name: "Microsoft India",
    industry: "Technology",
    location: "Hyderabad",
    size: "20,000+",
    founded_year: 1990,
    website: "https://www.microsoft.com/en-in",
    description: "R&D, cloud, software, offices in 10 cities",
  },
  {
    name: "Google India",
    industry: "Technology",
    location: "Bangalore",
    size: "5,000+",
    founded_year: 2004,
    website: "https://about.google/intl/ALL_in/",
    description: "Search, cloud, ads, R&D, offices in major metros",
  },
  {
    name: "Zoho Corporation",
    industry: "Technology",
    location: "Chennai",
    size: "10,000+",
    founded_year: 1996,
    website: "https://www.zoho.com/",
    description: "Global SaaS product company",
  },
  {
    name: "TCS (Tata Consultancy Services)",
    industry: "IT Services",
    location: "Mumbai",
    size: "600,000+",
    founded_year: 1968,
    website: "https://www.tcs.com/",
    description: "Leading IT, consulting, and outsourcing firm",
  },
  {
    name: "Infosys",
    industry: "IT Services",
    location: "Bangalore",
    size: "343,000+",
    founded_year: 1981,
    website: "https://www.infosys.com/",
    description: "Multinational IT services and consulting",
  },
  {
    name: "Wipro",
    industry: "IT Services",
    location: "Bangalore",
    size: "250,000+",
    founded_year: 1945,
    website: "https://www.wipro.com/",
    description: "IT, consulting, digital services",
  },
  {
    name: "HCL Technologies",
    industry: "IT Services",
    location: "Noida",
    size: "220,000+",
    founded_year: 1976,
    website: "https://www.hcltech.com/",
    description: "Global IT, engineering, outsourcing",
  },
  {
    name: "Tech Mahindra",
    industry: "IT Services",
    location: "Pune",
    size: "150,000+",
    founded_year: 1986,
    website: "https://www.techmahindra.com/",
    description: "Digital transformation, IT services",
  },
  {
    name: "Mahindra & Mahindra",
    industry: "Automotive",
    location: "Mumbai",
    size: "42,875+",
    founded_year: 1945,
    website: "https://www.mahindra.com/",
    description: "Automotive, farm equipment, services",
  },
  {
    name: "Larsen & Toubro (L&T)",
    industry: "Conglomerate",
    location: "Mumbai",
    size: "45,000+",
    founded_year: 1938,
    website: "https://www.larsentoubro.com/",
    description: "Engineering, construction, IT, finance",
  },
  {
    name: "Reliance Industries",
    industry: "Conglomerate",
    location: "Mumbai",
    size: "229,000+",
    founded_year: 1966,
    website: "https://www.ril.com/",
    description: "Conglomerate: oil, retail, telecom, digital",
  },
  {
    name: "Flipkart",
    industry: "E-Commerce",
    location: "Bangalore",
    size: "15,000+",
    founded_year: 2007,
    website: "https://www.flipkart.com/",
    description: "E-commerce giant",
  },
  {
    name: "BYJU'S",
    industry: "E-Learning",
    location: "Bangalore",
    size: "10,000+",
    founded_year: 2011,
    website: "https://byjus.com/",
    description: "India's leading ed-tech company",
  },
  {
    name: "Swiggy",
    industry: "Food Tech",
    location: "Bangalore",
    size: "5,000+",
    founded_year: 2014,
    website: "https://www.swiggy.com/",
    description: "Online food ordering, delivery platform",
  },
  {
    name: "Zomato",
    industry: "Food Tech",
    location: "Gurgaon",
    size: "4,000+",
    founded_year: 2008,
    website: "https://www.zomato.com/",
    description: "Restaurant discovery, food delivery",
  },
  {
    name: "Ola Cabs",
    industry: "Transport",
    location: "Bangalore",
    size: "7,000+",
    founded_year: 2010,
    website: "https://www.olacabs.com/",
    description: "App-based taxi aggregator",
  },
  {
    name: "Paytm",
    industry: "Fintech",
    location: "Noida",
    size: "6,500+",
    founded_year: 2010,
    website: "https://paytm.com/",
    description: "Payments, digital wallet, e-commerce",
  },
  {
    name: "PhonePe",
    industry: "Fintech",
    location: "Bangalore",
    size: "5,000+",
    founded_year: 2015,
    website: "https://www.phonepe.com/",
    description: "Digital payments, UPI platform",
  },
  {
    name: "Freshworks",
    industry: "Software",
    location: "Chennai",
    size: "5,000+",
    founded_year: 2010,
    website: "https://www.freshworks.com/",
    description: "SaaS products for business",
  },
  {
    name: "Mindtree",
    industry: "IT Services",
    location: "Bangalore",
    size: "38,000+",
    founded_year: 1999,
    website: "https://www.mindtree.com/",
    description: "IT consultancy, digital transformation",
  },
  {
    name: "Mphasis",
    industry: "IT Services",
    location: "Bangalore",
    size: "37,000+",
    founded_year: 1998,
    website: "https://www.mphasis.com/",
    description: "IT services, cloud, cognitive solutions",
  },
  {
    name: "Capgemini India",
    industry: "IT Services",
    location: "Mumbai",
    size: "180,000+",
    founded_year: 1997,
    website: "https://www.capgemini.com/in-en/",
    description: "IT, consulting, outsourcing (India unit)",
  },
  {
    name: "Amazon India",
    industry: "E-Commerce",
    location: "Bangalore",
    size: "100,000+",
    founded_year: 2013,
    website: "https://www.amazon.in/",
    description: "Online marketplace, cloud services",
  },
  {
    name: "EY (Ernst & Young) India",
    industry: "Consulting",
    location: "Mumbai",
    size: "50,000+",
    founded_year: 2002,
    website: "https://www.ey.com/en_in",
    description: "Audit, consulting, advisory (India ops)",
  },
  {
    name: "KPMG India",
    industry: "Consulting",
    location: "Mumbai",
    size: "20,000+",
    founded_year: 1993,
    website: "https://home.kpmg/in/en/home.html",
    description: "Audit, tax, legal, advisory",
  },
  {
    name: "Genpact",
    industry: "IT Services",
    location: "Gurgaon",
    size: "115,000+",
    founded_year: 1997,
    website: "https://www.genpact.com/",
    description: "Global business process management",
  },
  {
    name: "Tata Steel",
    industry: "Manufacturing",
    location: "Mumbai, Jamshedpur",
    size: "77,000+",
    founded_year: 1907,
    website: "https://www.tatasteel.com/",
    description: "Major steel producer in India",
  },
  {
    name: "Godrej Group",
    industry: "Conglomerate",
    location: "Mumbai",
    size: "28,000+",
    founded_year: 1897,
    website: "https://www.godrej.com/",
    description: "Consumer goods, industrial engineering",
  },
  {
    name: "ICICI Bank",
    industry: "Banking",
    location: "Mumbai",
    size: "97,000+",
    founded_year: 1994,
    website: "https://www.icicibank.com/",
    description: "Large private sector bank",
  },
  {
    name: "Axis Bank",
    industry: "Banking",
    location: "Mumbai",
    size: "85,000+",
    founded_year: 1993,
    website: "https://www.axisbank.com/",
    description: "Leading private sector bank",
  },
  {
    name: "HDFC Ltd/BANK",
    industry: "Banking",
    location: "Mumbai",
    size: "117,000+",
    founded_year: 1994,
    website: "https://www.hdfcbank.com/",
    description: "Leading bank and housing finance firm",
  },
  {
    name: "BharatPe",
    industry: "Fintech",
    location: "Delhi",
    size: "1,000+",
    founded_year: 2018,
    website: "https://www.bharatpe.com/",
    description: "Merchant payments and financial tech",
  },
  {
    name: "Razorpay",
    industry: "Fintech",
    location: "Bangalore",
    size: "1,700+",
    founded_year: 2014,
    website: "https://www.razorpay.com/",
    description: "Online payment gateway solutions",
  },
  {
    name: "Dream11",
    industry: "Sports Tech",
    location: "Mumbai",
    size: "1,000+",
    founded_year: 2008,
    website: "https://dream11.com/",
    description: "Fantasy sports platform",
  },
];

async function seed() {
  try {
    // Clear existing data
    await pool.query('DELETE FROM companies');
    
    // Insert sample companies
    const insertQuery = `
      INSERT INTO companies (name, industry, location, size, founded_year, website, description)
      VALUES ($1, $2, $3, $4, $5, $6, $7)
    `;

    for (const company of sampleCompanies) {
      await pool.query(insertQuery, [
        company.name,
        company.industry,
        company.location,
        company.size,
        company.founded_year,
        company.website,
        company.description
      ]);
    }

    console.log(`✅ Seeded ${sampleCompanies.length} companies successfully`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
}

seed();

